### ISSUE TITLE
从中间粘贴，有下移阴影，摇一摇取消有问题

### ISSUE THREAD

**Issue by JmoVxia** [jalyResource/GrowTextView#1]
![1](https://user-images.githubusercontent.com/19339708/55370987-15424800-552f-11e9-9b23-f1d7428b3feb.gif)

**Comment by wuzhenli** [comment]
已经修复了这两个问题。多谢提醒。😆

**Comment by wuzhenli** [comment]
摇晃-取消输入框晃动，是监听键盘位置做动画的 UIViewAnimationOptions 未设置妥当。
输入框从文字中间粘贴有奇怪的动画：设置 textView.pasteDelegate 实现一个方法即可.
